"section.noPermission": "你没有权限执行该命令"
"section.set.success": "设置%s.%s为%s"
"section.exit.fail": "你无法退出坑(%s)"
"section.noIn": "你没有下坑呢"
"section.leave.success": "%s离开了坑(%s)"
"section.create.fail": "开坑失败!"
"section.exit.success": "%s退出了坑(%s)"
"section.hadExit": "这坑已经有人开了..."
"section.noExist": "&c没有这个坑吧..."
"section.load.success": "%s: 存档恢复完毕..."
"section.set.fail": "设置失败"
"section.join.had": "你已经加入坑(%s)了"
"section.join.fail": "加入失败"
"section.in": "你现在坑(%s)里了"
"section.create.success": "开坑成功!"
"section.save.success": "%s: 存档保存完毕..."
"section.join.success": "%s加入了坑(%s)"
"section.delete.success": "你删除了坑(%s)"
"section.delete.fail": "删除了坑失败"
